spring:
datasource:
url: jdbc:h2:mem:testdb

# storing in file
#    url: spring.datasource.url=jdbc:h2:file:/data/demo
driverClassName: org.h2.Driver
data-username: sa
password: password
jpa:
database-platform: org.hibernate.dialect.H2Dialect
h2:
console:
enabled: true
